import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const currentDir = dirname(fileURLToPath(import.meta.url))

export default defineNuxtConfig({
  $meta: {
    name: 'businesslens-nuxt-report-viewer'
  },
  extends: [join(currentDir, '../theme')],
  ui: { prose: true },
  css: [
    join(currentDir, './app/assets/report-structure.css'),
    join(currentDir, './app/assets/report-viewer.css'),
    join(currentDir, './app/assets/report-topology.css')
  ],
  // The bundled local viewer is a generated SPA with no icon endpoint at
  // runtime. Explicitly include icons referenced by inherited components.
  icon: {
    clientBundle: {
      icons: [
        'lucide:align-justify',
        'lucide:app-window',
        'lucide:arrow-down',
        'lucide:arrow-left',
        'lucide:arrow-right',
        'lucide:arrow-up',
        'lucide:arrow-up-down',
        'lucide:audio-lines',
        'lucide:ban',
        'lucide:book-a',
        'lucide:book-open',
        'lucide:bot',
        'lucide:box',
        'lucide:braces',
        'lucide:check',
        'lucide:chevron-down',
        'lucide:chevron-left',
        'lucide:chevron-right',
        'lucide:chevron-up',
        'lucide:circle-dot-dashed',
        'lucide:circle-question-mark',
        'lucide:circle-small',
        'lucide:clipboard-list',
        'lucide:cog',
        'lucide:corner-down-right',
        'lucide:cpu',
        'lucide:copy',
        'lucide:copy-check',
        'lucide:eye',
        'lucide:eye-off',
        'lucide:file',
        'lucide:file-code',
        'lucide:external-link',
        'lucide:file-question',
        'lucide:file-diff',
        'lucide:file-text',
        'lucide:filter-x',
        'lucide:funnel',
        'lucide:focus',
        'lucide:folder',
        'lucide:folder-open',
        'lucide:folder-root',
        'lucide:gavel',
        'lucide:git-branch',
        'lucide:git-fork',
        'lucide:check',
        'lucide:globe',
        'lucide:hand',
        'lucide:house',
        'lucide:image',
        'lucide:key-round',
        'lucide:land-plot',
        'lucide:layers',
        'lucide:layout-grid',
        'lucide:layout-list',
        'lucide:layout-panel-left',
        'lucide:layout-template',
        'lucide:link',
        'lucide:list-checks',
        'lucide:list-filter',
        'lucide:list-ordered',
        'lucide:loader-circle',
        'lucide:menu',
        'lucide:messages-square',
        'lucide:microscope',
        'lucide:minus',
        'lucide:square-minus',
        'lucide:monitor',
        'lucide:mouse-pointer-click',
        'lucide:network',
        'lucide:panel-right-open',
        'lucide:panel-left-open',
        'lucide:panel-left-close',
        'lucide:plug',
        'lucide:plus',
        'lucide:refresh-cw',
        'lucide:route',
        'lucide:rows-3',
        'lucide:maximize-2',
        'lucide:minimize-2',
        'lucide:maximize',
        'lucide:minimize',
        'lucide:grid-2x2',
        'lucide:link-2',
        'lucide:waypoints',
        'lucide:scale',
        'lucide:scan',
        'lucide:search',
        'lucide:shapes',
        'lucide:smartphone',
        'lucide:split',
        'lucide:table',
        'lucide:terminal',
        'lucide:user-round',
        'lucide:users',
        'lucide:webhook',
        'lucide:x',
        'lucide:zap'
      ]
    }
  }
})
