/**
 * The vocabulary registry generated from the terms each documentation page owns.
 *
 * A term is defined in the frontmatter of the page that explains it, so the
 * one-line definition sits in the same file as the narrative it summarizes and
 * "explained in exactly one place" is a property of the filesystem rather than
 * a rule someone remembers. The report viewer's registry is generated from
 * those declarations and shared by inline definitions and the Vocabulary panel.
 *
 * A page declares:
 *
 *   terms:
 *     - term: Arc
 *       anchor: states-and-the-lifecycle-nobody-authors
 *       definition: One allowed move between two States, and the Step that makes it.
 *
 * `on` scopes a term explained on two pages — Trigger belongs to both Scenario
 * types — and only ever disambiguates the slug; the reader still sees "Trigger".
 *
 * `aliases` lists the shorthand the documentation actually writes for a term —
 * "Rule" for a Business Rule — so a definition using it still links. Names,
 * aliases and their plurals also make the term searchable in the report.
 * An alias that two terms would claim links to neither, exactly like a shared name.
 */
import { readFile, readdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { parse as parseYaml } from 'yaml'

/** The generated registry, named once so the builder and the check agree. */
export const VOCABULARY_MODULE = 'layers/nuxt/report-viewer/app/utils/vocabulary.generated.ts'

/**
 * A definition is popover copy, not a paragraph: the page it points at holds
 * the explanation, and a definition that outgrows one line is evidence the term
 * wanted a section rather than a row.
 */
const DEFINITION_LIMIT = 150

const BANNER = 'Generated by `npm run vocabulary` from the `terms:` frontmatter of the owning documentation pages.'

/** Frontmatter, body, and the headings the body actually has. */
export function splitDoc(source) {
  const match = source.match(/^---\n([\s\S]*?)\n---\n?/)
  if (!match) return { frontmatter: null, body: source }
  return { frontmatter: match[1], body: source.slice(match[0].length) }
}

/**
 * Headings outside fenced code, because every resource page shows an example
 * file whose own `## Trigger` is not a heading of the page.
 */
export function headingsOf(body) {
  const headings = []
  let fence = null
  for (const line of body.split('\n')) {
    const fenceMatch = line.match(/^\s*(`{3,}|~{3,})/)
    if (fenceMatch) {
      const marker = fenceMatch[1][0]
      if (!fence) fence = marker
      else if (fence === marker) fence = null
      continue
    }
    if (fence) continue
    const heading = line.match(/^#{2,6}\s+(.+?)\s*$/)
    if (heading) headings.push(heading[1])
  }
  return headings
}

/** The anchor a docs heading gets, the way the docs site slugs it. */
export function anchorFor(heading) {
  return heading
    .replace(/`([^`]*)`/g, '$1')
    .replace(/\[([^\]]*)]\([^)]*\)/g, '$1')
    .replace(/[*_]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
}

/** The same names and plurals serve definition links and vocabulary search. */
function termForms(term) {
  return [...new Set([term.term, ...term.aliases].flatMap(name => {
    const plural = /[^aeiou]y$/.test(name) ? `${name.slice(0, -1)}ies` : `${name}s`
    return [name, plural]
  }))]
}

/**
 * The words a definition can point at, and the rules for deciding it meant one.
 *
 * A definition that leans on another term is where a reader gets stuck twice, so
 * the mention is resolved once here and every surface renders the same links.
 * Matching is deliberately conservative, because a wrong link is worse than none:
 *
 * - **Case-sensitive.** The documentation capitalizes a resource type where it
 *   means the type, so "a state of the view itself" stays prose while "Never a
 *   State of the thing" links. Lowercase is the author's way of saying they meant
 *   the ordinary English word.
 * - **Never at position 0.** A capital at the start of a sentence says nothing
 *   about intent, and that is the only false positive the corpus had — "Who may
 *   enter an Experience" is not pointing at the Business Rule section.
 * - **Longest form first, no overlaps, one link per target.** "Journey Scenario"
 *   wins over "Journey", and a definition never turns into a wall of links.
 * - **An ambiguous word links nowhere.** Trigger, Outcome, Route, Decision point
 *   and Edge case each name two terms, and nothing in a sentence says which.
 */
function mentionForms(terms) {
  const owners = new Map()
  for (const term of terms) {
    for (const form of termForms(term)) {
      owners.set(form, (owners.get(form) ?? []).concat(term.slug))
    }
  }
  return [...owners]
    .filter(([, slugs]) => slugs.length === 1)
    .map(([form, slugs]) => ({
      form,
      slug: slugs[0],
      pattern: new RegExp(`\\b${form.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'g')
    }))
    .sort((left, right) => right.form.length - left.form.length)
}

function mentionsIn(definition, selfSlug, forms) {
  const found = []
  for (const { form, slug, pattern } of forms) {
    if (slug === selfSlug || found.some(mention => mention.slug === slug)) continue
    pattern.lastIndex = 0
    let match
    while ((match = pattern.exec(definition))) {
      const from = match.index
      const to = from + form.length
      if (from === 0) continue
      if (found.some(mention => from < mention.to && to > mention.from)) continue
      found.push({ from, to, slug })
      break
    }
  }
  return found.sort((left, right) => left.from - right.from)
}

/** The stable id a surface addresses a term by. `on` only disambiguates. */
export function slugFor(term, on) {
  const base = term
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
  return on ? `${on}-${base}` : base
}

/**
 * Every term every page owns, in docs order, with everything wrong about them.
 *
 * Errors are returned rather than thrown so `check` reports all of them at once
 * beside its other findings.
 */
export async function readVocabulary(root) {
  const errors = []
  const terms = []
  const seen = new Map()

  const names = (await readdir(resolve(root, 'docs')))
    .filter(name => name.endsWith('.md'))
    .sort()

  const pages = []
  for (const name of names) {
    const source = await readFile(resolve(root, 'docs', name), 'utf8')
    const { frontmatter, body } = splitDoc(source)
    if (!frontmatter) continue
    let data
    try {
      data = parseYaml(frontmatter)
    } catch {
      continue // the frontmatter contract check reports this already
    }
    if (!data || typeof data !== 'object' || Array.isArray(data)) continue
    pages.push({ name, data, body })
  }

  pages.sort((left, right) => (left.data.order ?? 0) - (right.data.order ?? 0))

  for (const page of pages) {
    const declared = page.data.terms
    if (declared === undefined) continue
    if (page.data.group === 'CLI') {
      errors.push(`docs/${page.name} CLI pages must not declare "terms"`)
      continue
    }
    if (!Array.isArray(declared)) {
      errors.push(`docs/${page.name} frontmatter "terms" must be a list`)
      continue
    }
    const anchors = new Set(headingsOf(page.body).map(anchorFor))
    let lead = null
    for (const entry of declared) {
      const at = `docs/${page.name} terms`
      if (!entry || typeof entry !== 'object' || Array.isArray(entry)) {
        errors.push(`${at} entry must be a mapping`)
        continue
      }
      const { term, definition, anchor, on, aliases } = entry
      if (typeof term !== 'string' || !term.trim()) {
        errors.push(`${at} entry is missing "term"`)
        continue
      }
      if (typeof definition !== 'string' || !definition.trim()) {
        errors.push(`${at} "${term}" is missing "definition"`)
        continue
      }
      if (definition.includes('\n')) {
        errors.push(`${at} "${term}" definition must be one line`)
      }
      if (definition.length > DEFINITION_LIMIT) {
        errors.push(
          `${at} "${term}" definition is ${definition.length} characters; `
          + `keep it under ${DEFINITION_LIMIT} and let the page say the rest`
        )
      }
      if (!/[.?]$/.test(definition.trim())) {
        errors.push(`${at} "${term}" definition must end in a full stop`)
      }
      if (anchor !== undefined && (typeof anchor !== 'string' || !anchors.has(anchor))) {
        errors.push(`${at} "${term}" anchor "${anchor}" is not a heading in docs/${page.name}`)
      }
      if (on !== undefined && (typeof on !== 'string' || !on.trim())) {
        errors.push(`${at} "${term}" on must be a non-empty string`)
        continue
      }
      if (aliases !== undefined
        && (!Array.isArray(aliases) || aliases.some(alias => typeof alias !== 'string' || !alias.trim()))) {
        errors.push(`${at} "${term}" aliases must be a list of non-empty strings`)
        continue
      }
      if (lead === null && on !== undefined) {
        errors.push(
          `${at} "${term}" is the page's lead and cannot be scoped with "on". `
          + 'A page leads with the term it is named for, which no other page shares.'
        )
        continue
      }
      const slug = slugFor(term, on)
      const previous = seen.get(slug)
      if (previous) {
        errors.push(
          `${at} "${term}" repeats the term ${previous} already defines. `
          + 'One page owns a term; scope it with "on" when two genuinely do.'
        )
        continue
      }
      seen.set(slug, at)
      if (lead === null) lead = slug
      terms.push({
        slug,
        term: term.trim(),
        definition: definition.trim(),
        page: page.name.replace(/\.md$/, ''),
        pageTitle: typeof page.data.title === 'string' ? page.data.title : page.name,
        group: typeof page.data.group === 'string' ? page.data.group : '',
        anchor: typeof anchor === 'string' ? anchor : '',
        aliases: Array.isArray(aliases) ? aliases.map(alias => alias.trim()) : [],
        mentions: []
      })
    }
  }

  /* Mentions resolve against the finished set: a definition may point at a term
     declared on a page the reader has not reached, or read yet. */
  const forms = mentionForms(terms)
  for (const term of terms) {
    term.mentions = mentionsIn(term.definition, term.slug, forms)
  }

  return { terms, errors }
}

/**
 * Each page's lead: the first term it declares.
 *
 * For pages included in the panel, the report states it in the section head, so
 * reordering a page's `terms:` is a visible change to the generated leads rather
 * than a silent change to what the panel calls a section's meaning.
 */
export function leadsOf(terms) {
  const leads = new Map()
  for (const term of terms) if (!leads.has(term.page)) leads.set(term.page, term.slug)
  return leads
}

/** The registry the report viewer's popovers and vocabulary panel read. */
export function renderModule(terms) {
  const entries = terms.map(term => {
    const fields = [
      `term: ${JSON.stringify(term.term)}`,
      `searchNames: ${JSON.stringify(termForms(term))}`,
      `definition: ${JSON.stringify(term.definition)}`,
      `page: ${JSON.stringify(term.page)}`,
      `pageTitle: ${JSON.stringify(term.pageTitle)}`,
      `group: ${JSON.stringify(term.group)}`,
      `anchor: ${JSON.stringify(term.anchor)}`,
      `mentions: [${term.mentions.map(m => `[${m.from}, ${m.to}, ${JSON.stringify(m.slug)}]`).join(', ')}]`
    ]
    return `  ${JSON.stringify(term.slug)}: { ${fields.join(', ')} }`
  })

  const leads = [...leadsOf(terms)]
    .map(([page, slug]) => `  ${JSON.stringify(page)}: ${JSON.stringify(slug)}`)

  return `/**
 * ${BANNER}
 *
 * Do not edit by hand: run \`npm run vocabulary\` after changing a page's terms,
 * and \`npm run check\` fails while this file and docs/ disagree.
 */

export interface VocabularyEntry {
  /** The word as the report renders it. */
  term: string
  /** The term's name, aliases, and their plurals, generated from its owning page. */
  searchNames: readonly string[]
  /** One line. The owning page carries the explanation. */
  definition: string
  /** The docs page that owns it, and the heading to land on. */
  page: string
  anchor: string
  /** How the owning page names itself, and the sidebar cluster it sits in. */
  pageTitle: string
  group: string
  /**
   * Where this definition leans on another term: from, to, slug — slices of the
   * definition above. Resolved once at generation so every surface links the
   * same words, and left as offsets so the definition stays one searchable
   * string.
   */
  mentions: readonly (readonly [number, number, string])[]
}

export const VOCABULARY = {
${entries.join(',\n')}
} as const satisfies Record<string, VocabularyEntry>

/** Every addressable term. A surface naming one that is gone fails to compile. */
export type VocabularySlug = keyof typeof VOCABULARY

/**
 * Each page's first declared term. For pages included in the vocabulary panel,
 * it appears in the section head, with the page's other terms beneath it.
 */
export const VOCABULARY_LEADS: Readonly<Record<string, VocabularySlug>> = {
${leads.join(',\n')}
}
`
}
