/**
 * Generated by `npm run vocabulary` from the `terms:` frontmatter of the pages below.
 *
 * Do not edit by hand: run `npm run vocabulary` after changing a page's terms,
 * and `npm run check` fails while this file and docs/ disagree.
 */

export interface VocabularyEntry {
  /** The word as the report renders it. */
  term: string
  /** One line. The owning page carries the explanation. */
  definition: string
  /** The docs page that owns it, and the heading to land on. */
  page: string
  anchor: string
  /** How the owning page names itself, and the sidebar cluster it sits in. */
  pageTitle: string
  group: string
  /**
   * Where this definition leans on another term: from, to, slug — slices of the
   * definition above. Resolved once at generation so every surface links the
   * same words, and left as offsets so the definition stays one searchable
   * string.
   */
  mentions: readonly (readonly [number, number, string])[]
}

export const VOCABULARY = {
  "product-model": { term: "Product Model", definition: "The .businesslens/ folder: one coherent product described in Markdown, tracked in Git, and free to cite the repository's code.", page: "product-model", pageTitle: "Model overview", group: "Product Model", anchor: "the-shape-of-a-model", mentions: [] },
  "intent": { term: "Intent", definition: "Why a resource exists and which outcome it protects, never a restatement of what it does.", page: "product-model", pageTitle: "Model overview", group: "Product Model", anchor: "authoring-conventions", mentions: [] },
  "coverage": { term: "Coverage", definition: "How broadly the model has been authored, as draft, partial or complete, and why the known gaps remain.", page: "product-model", pageTitle: "Model overview", group: "Product Model", anchor: "coverage", mentions: [] },
  "resource-type": { term: "Resource type", definition: "A category of resource, such as Entity or Capability, determined by the file's location in the Product Model.", page: "product-model", pageTitle: "Model overview", group: "Product Model", anchor: "what-belongs-in-a-model", mentions: [[32, 38, "entity"], [42, 52, "capability"], [95, 108, "product-model"]] },
  "topology": { term: "Topology", definition: "The report's visual map of resources and their connections, with named views that answer specific questions about the model.", page: "product-model", pageTitle: "Model overview", group: "Product Model", anchor: "reading-the-report", mentions: [] },
  "neighbourhood": { term: "Neighbourhood", definition: "One resource drawn on the Topology canvas with everything that touches it.", page: "product-model", pageTitle: "Model overview", group: "Product Model", anchor: "reading-the-report", mentions: [[26, 34, "topology"]] },
  "product": { term: "Product", definition: "The one coherent value promise this model describes, and the boundary drawn around it.", page: "product", pageTitle: "Product", group: "Product Model", anchor: "", mentions: [] },
  "entity": { term: "Entity", definition: "A distinct thing the Product keeps or reasons about, including the people and systems that act on it.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "", mentions: [[21, 28, "product"]] },
  "actor": { term: "Actor", definition: "An Entity that acts on the Product. Actor is a role a thing plays where it acts, never a resource type of its own.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "actors-an-entity-that-acts", mentions: [[3, 9, "entity"], [27, 34, "product"]] },
  "entity-kind": { term: "Entity kind", definition: "Whether an Entity that acts on the Product is a person or a system.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "actors-an-entity-that-acts", mentions: [[11, 17, "entity"], [35, 42, "product"]] },
  "acts": { term: "Acts", definition: "Which side of the boundary an Actor acts from: internal to the organisation running the Product, or external to it.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "external-systems-direction-decides", mentions: [[30, 35, "actor"], [88, 95, "product"]] },
  "information-kept": { term: "Information kept", definition: "Named facts the Product keeps about an Entity. Each can be referenced by name; storage details and data types stay outside the model.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "the-file", mentions: [[16, 23, "product"], [39, 45, "entity"]] },
  "state": { term: "State", definition: "A named condition an Entity can be in, such as Pending or Refunded. Scenario Steps define how it moves between States.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[21, 27, "entity"], [77, 82, "step"]] },
  "arc": { term: "Arc", definition: "A move a Step makes: into a State, out of one, or between two. Nothing declares arcs; the report composes them from the Scenarios.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[9, 13, "step"], [28, 33, "state"]] },
  "lifecycle": { term: "Lifecycle", definition: "An Entity's States and Arcs, showing how it is created, changes state, or is removed, derived from Scenario Steps across the model.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[3, 9, "entity"], [12, 18, "state"], [23, 27, "arc"], [108, 113, "step"]] },
  "relation": { term: "Relation", definition: "A relationship between Entities, such as Shopper owns Orders, stating how many instances can relate on each side.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "relations", mentions: [[23, 31, "entity"]] },
  "changed-by": { term: "Changed by", definition: "The Capabilities whose Steps create, change, or remove this thing.", page: "entities", pageTitle: "Entities", group: "Product Model", anchor: "relations", mentions: [[4, 16, "capability"], [23, 28, "step"]] },
  "interface": { term: "Interface", definition: "A supported way for Actors to interact with the Product, such as a web app, a CLI, or a partner API.", page: "interfaces", pageTitle: "Interfaces", group: "Product Model", anchor: "", mentions: [[20, 26, "actor"], [48, 55, "product"]] },
  "interface-type": { term: "Interface type", definition: "The form an Interface takes: web, mobile app, desktop app, CLI, API, webhook, messaging, voice, device, or agent.", page: "interfaces", pageTitle: "Interfaces", group: "Product Model", anchor: "the-file", mentions: [[12, 21, "interface"]] },
  "capability-boundary": { term: "Capability boundary", definition: "What an Interface, Experience, or Screen supports and excludes. Capability availability is declared on each Capability.", page: "interfaces", pageTitle: "Interfaces", group: "Product Model", anchor: "the-file", mentions: [[8, 17, "interface"], [19, 29, "experience"], [34, 40, "screen"], [64, 74, "capability"]] },
  "entry-point": { term: "Entry point", definition: "A Product-facing route or address where an Actor arrives, such as a path, a deep link, or a command.", page: "interfaces", pageTitle: "Interfaces", group: "Product Model", anchor: "the-file", mentions: [[2, 9, "product"], [43, 48, "actor"]] },
  "experience": { term: "Experience", definition: "A stable context for using the Product within one Interface, with a defined audience, access mode, and capability boundary.", page: "experiences", pageTitle: "Experiences", group: "Product Model", anchor: "", mentions: [[31, 38, "product"], [50, 59, "interface"]] },
  "access-mode": { term: "Access mode", definition: "Who may enter an Experience: public, authenticated, or restricted.", page: "experiences", pageTitle: "Experiences", group: "Product Model", anchor: "the-file", mentions: [[17, 27, "experience"]] },
  "screen": { term: "Screen", definition: "A meaningful visual view, named in the Product's own words, directly under an Interface or inside one of its Experiences.", page: "screens", pageTitle: "Screens", group: "Product Model", anchor: "", mentions: [[39, 46, "product"], [78, 87, "interface"], [109, 120, "experience"]] },
  "view-state": { term: "View state", definition: "A condition of a Screen, such as empty, populated, or unauthorized. It describes the view rather than an Entity's Lifecycle.", page: "screens", pageTitle: "Screens", group: "Product Model", anchor: "view-states-are-the-views-never-the-things", mentions: [[17, 23, "screen"], [105, 111, "entity"], [114, 123, "lifecycle"]] },
  "domain": { term: "Domain", definition: "A subject area of the Product, such as ordering or billing, that classifies related Capabilities and Entities.", page: "domains", pageTitle: "Domains", group: "Product Model", anchor: "", mentions: [[22, 29, "product"], [84, 96, "capability"], [101, 109, "entity"]] },
  "boundary": { term: "Boundary", definition: "What a Domain takes in and what it leaves out, stated in the Product's own words.", page: "domains", pageTitle: "Domains", group: "Product Model", anchor: "the-file", mentions: [[7, 13, "domain"], [61, 68, "product"]] },
  "capability": { term: "Capability", definition: "A durable ability of the Product: what it can do, independent of any one route, command, or module.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "", mentions: [[25, 32, "product"]] },
  "capability-scenario": { term: "Capability Scenario", definition: "One observable acceptance case for a Capability: a trigger, typed Steps, and an outcome.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "capability-scenarios", mentions: [[37, 47, "capability"], [66, 71, "step"]] },
  "context": { term: "Context", definition: "Where behavior is available, occurs, or is constrained: one Interface, Experience, or Screen. How specific it must be depends on what uses it.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "availability", mentions: [[60, 69, "interface"], [71, 81, "experience"], [86, 92, "screen"]] },
  "step": { term: "Step", definition: "One action or condition in a Scenario. Actions are performed by an Actor or the Product; effects on Entities are recorded explicitly.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "what-a-step-does-to-the-products-things", mentions: [[67, 72, "actor"], [80, 87, "product"], [100, 108, "entity"]] },
  "ends-with": { term: "Ends with", definition: "The last creation, change, or removal of each Entity instance in a Scenario, including the resulting State when specified.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "what-a-step-does-to-the-products-things", mentions: [[46, 52, "entity"], [101, 106, "state"]] },
  "scenario-kind": { term: "Scenario kind", definition: "A category for a Scenario, such as primary or edge, defined in the model's taxonomies.yaml.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-trigger": { term: "Trigger", definition: "The observable condition that starts the Scenario.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-outcome": { term: "Outcome", definition: "The observable result once the Scenario has run.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-route": { term: "Route", definition: "One named way the same Steps play out in different places. A route varies Context only; different Steps mean a different Scenario.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "routes-steps-and-context-places", mentions: [[23, 28, "step"], [74, 81, "context"]] },
  "capability-scenario-decision-point": { term: "Decision point", definition: "A question with alternative branches that lead to the same Capability Scenario outcome. A different outcome requires another Scenario.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "capability-scenario-decision-points", mentions: [[59, 78, "capability-scenario"]] },
  "capability-scenario-edge-case": { term: "Edge case", definition: "A condition and its consequence recorded within a Scenario, without changing its path.", page: "capabilities", pageTitle: "Capabilities", group: "Product Model", anchor: "the-capability-scenario-file", mentions: [] },
  "journey": { term: "Journey", definition: "An Actor goal whose successful completion requires several Capabilities working together.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "", mentions: [[3, 8, "actor"], [59, 71, "capability"]] },
  "journey-scenario": { term: "Journey Scenario", definition: "One path through a Journey, ending with its goal achieved or not achieved.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "journey-scenarios", mentions: [[19, 26, "journey"]] },
  "success-criterion": { term: "Success criterion", definition: "How you know the Journey's goal was met.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "the-file", mentions: [[17, 24, "journey"]] },
  "leaves-behind": { term: "Leaves behind", definition: "The Entity instances created, changed, or removed by a Journey's achieved paths, with final States when specified.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "the-file", mentions: [[4, 10, "entity"], [55, 62, "journey"], [92, 98, "state"]] },
  "journey-scenario-trigger": { term: "Trigger", definition: "The observable condition that starts the Journey Scenario.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "the-journey-scenario-file", mentions: [[41, 57, "journey-scenario"]] },
  "journey-scenario-outcome": { term: "Outcome", definition: "Where the path ends, and whether the Journey's goal was achieved.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "the-journey-scenario-file", mentions: [[37, 44, "journey"]] },
  "result": { term: "Result", definition: "Whether this path achieves the Journey's goal: achieved, or not-achieved.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "the-journey-scenario-file", mentions: [[31, 38, "journey"]] },
  "journey-scenario-route": { term: "Route", definition: "One named way the same Steps play out in different places. A route varies Context only; different Steps mean a different Journey Scenario.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "steps-and-routes", mentions: [[23, 28, "step"], [74, 81, "context"], [121, 137, "journey-scenario"]] },
  "journey-scenario-decision-point": { term: "Decision point", definition: "A question with alternative branches that preserve the Journey Scenario's Capability sequence and outcome.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "journey-scenario-decision-points", mentions: [[55, 71, "journey-scenario"], [74, 84, "capability"]] },
  "journey-scenario-edge-case": { term: "Edge case", definition: "A condition and its consequence recorded within a Scenario, without changing its path.", page: "journeys", pageTitle: "Journeys", group: "Product Model", anchor: "the-journey-scenario-file", mentions: [] },
  "business-rule": { term: "Business Rule", definition: "A durable assertion that must stay true, and the only place the model says who may act.", page: "business-rules", pageTitle: "Business Rules", group: "Product Model", anchor: "", mentions: [] },
  "applies-to": { term: "Applies to", definition: "What a Rule constrains: a resource, a Context it holds in, or an operation on a thing.", page: "business-rules", pageTitle: "Business Rules", group: "Product Model", anchor: "behavioral-and-context-targets", mentions: [[7, 11, "business-rule"], [38, 45, "context"]] },
  "operation": { term: "Operation", definition: "What may be done to a thing: creates, changes, removes, or reads. A Step calls it an effect; a Business Rule selects the same word as an operation.", page: "business-rules", pageTitle: "Business Rules", group: "Product Model", anchor: "entity-targets-an-operation-on-a-thing", mentions: [[68, 72, "step"], [95, 108, "business-rule"]] },
  "who-may": { term: "Who may", definition: "Who can perform an Entity operation and under what conditions. Each applicable permission Rule must have at least one grant that allows it.", page: "business-rules", pageTitle: "Business Rules", group: "Product Model", anchor: "permission", mentions: [[19, 25, "entity"], [90, 94, "business-rule"]] },
  "reference": { term: "Reference", definition: "A pointer to material outside the model, such as code, a spec, or a screenshot, saying what it is and why it is attached.", page: "references", pageTitle: "References", group: "Product Model", anchor: "asset-or-reference", mentions: [] },
  "reference-kind": { term: "Reference kind", definition: "What the referenced material is: code, prd, spec, proposal, doc, adr, visual, or research.", page: "references", pageTitle: "References", group: "Product Model", anchor: "kind-and-role", mentions: [] },
  "reference-role": { term: "Reference role", definition: "Why a Reference is attached: intent helps define the Product, implementation points to what was built, and context provides background.", page: "references", pageTitle: "References", group: "Product Model", anchor: "kind-and-role", mentions: [[6, 15, "reference"], [53, 60, "product"]] },
  "product-report": { term: "Product Report", definition: "The serialization of a Product Model. One format, two profiles: workspace keeps repository navigation, portable carries none of it.", page: "cli-export", pageTitle: "blueprint export", group: "CLI", anchor: "portable-export", mentions: [[23, 36, "product-model"]] },
  "blueprint": { term: "Blueprint", definition: "A portable Product Report. Publishing it in a catalog is a separate step.", page: "cli-contribute", pageTitle: "blueprint contribute", group: "CLI", anchor: "a-good-blueprint", mentions: [[11, 25, "product-report"]] }
} as const satisfies Record<string, VocabularyEntry>

/** Every addressable term. A surface naming one that is gone fails to compile. */
export type VocabularySlug = keyof typeof VOCABULARY

/**
 * Each page's first declared term. For pages included in the vocabulary panel,
 * it appears in the section head, with the page's other terms beneath it.
 */
export const VOCABULARY_LEADS: Readonly<Record<string, VocabularySlug>> = {
  "product-model": "product-model",
  "product": "product",
  "entities": "entity",
  "interfaces": "interface",
  "experiences": "experience",
  "screens": "screen",
  "domains": "domain",
  "capabilities": "capability",
  "journeys": "journey",
  "business-rules": "business-rule",
  "references": "reference",
  "cli-export": "product-report",
  "cli-contribute": "blueprint"
}
