/**
 * Generated by `npm run vocabulary` from the `terms:` frontmatter of the owning documentation pages.
 *
 * Do not edit by hand: run `npm run vocabulary` after changing a page's terms,
 * and `npm run check` fails while this file and docs/ disagree.
 */

export interface VocabularyEntry {
  /** The word as the report renders it. */
  term: string
  /** The term's name, aliases, and their plurals, generated from its owning page. */
  searchNames: readonly string[]
  /** One line. The owning page carries the explanation. */
  definition: string
  /** The docs page that owns it, and the heading to land on. */
  page: string
  anchor: string
  /** How the owning page names itself. */
  pageTitle: string
  /**
   * Where this definition leans on another term: from, to, slug — slices of the
   * definition above. Resolved once at generation so every surface links the
   * same words, and left as offsets so the definition stays one searchable
   * string.
   */
  mentions: readonly (readonly [number, number, string])[]
}

export const VOCABULARY = {
  "product-model": { term: "Product Model", searchNames: ["Product Model","Product Models"], definition: "The .businesslens/ folder: one coherent product described in Markdown, tracked in Git, and free to cite the repository's code.", page: "product-model", pageTitle: "Model overview", anchor: "the-shape-of-a-model", mentions: [] },
  "intent": { term: "Intent", searchNames: ["Intent","Intents"], definition: "Why a resource exists and which outcome it protects, never a restatement of what it does.", page: "product-model", pageTitle: "Model overview", anchor: "authoring-conventions", mentions: [] },
  "coverage": { term: "Coverage", searchNames: ["Coverage","Coverages"], definition: "How broadly the model has been authored, as draft, partial or complete, and why the known gaps remain.", page: "product-model", pageTitle: "Model overview", anchor: "coverage", mentions: [] },
  "resource-type": { term: "Resource type", searchNames: ["Resource type","Resource types"], definition: "A category of resource, such as Entity or Capability, determined by the file's location in the Product Model.", page: "product-model", pageTitle: "Model overview", anchor: "what-belongs-in-a-model", mentions: [[32, 38, "entity"], [42, 52, "capability"], [95, 108, "product-model"]] },
  "product": { term: "Product", searchNames: ["Product","Products"], definition: "The one coherent value promise this model describes, and the boundary drawn around it.", page: "product", pageTitle: "Product", anchor: "", mentions: [] },
  "entity": { term: "Entity", searchNames: ["Entity","Entities"], definition: "A distinct thing the Product keeps or reasons about, including the people and systems that act on it.", page: "entities", pageTitle: "Entities", anchor: "", mentions: [[21, 28, "product"]] },
  "actor": { term: "Actor", searchNames: ["Actor","Actors"], definition: "An Entity that acts on the Product. Actor is a role a thing plays where it acts, never a resource type of its own.", page: "entities", pageTitle: "Entities", anchor: "actors-an-entity-that-acts", mentions: [[3, 9, "entity"], [27, 34, "product"]] },
  "entity-kind": { term: "Entity kind", searchNames: ["Entity kind","Entity kinds"], definition: "Whether an Entity that acts on the Product is a person or a system.", page: "entities", pageTitle: "Entities", anchor: "actors-an-entity-that-acts", mentions: [[11, 17, "entity"], [35, 42, "product"]] },
  "acts": { term: "Acts", searchNames: ["Acts","Actss"], definition: "Which side of the boundary an Actor acts from: internal to the organisation running the Product, or external to it.", page: "entities", pageTitle: "Entities", anchor: "external-systems-direction-decides", mentions: [[30, 35, "actor"], [88, 95, "product"]] },
  "information-kept": { term: "Information kept", searchNames: ["Information kept","Information kepts"], definition: "Named facts the Product keeps about an Entity. Each can be referenced by name; storage details and data types stay outside the model.", page: "entities", pageTitle: "Entities", anchor: "the-file", mentions: [[16, 23, "product"], [39, 45, "entity"]] },
  "state": { term: "State", searchNames: ["State","States"], definition: "A named condition an Entity can be in, such as Pending or Refunded. Scenario Steps define how it moves between States.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[21, 27, "entity"], [77, 82, "step"]] },
  "left-here-by": { term: "Left here by", searchNames: ["Left here by","Left here bies"], definition: "Scenarios containing a Step that puts this Entity in this State, even if a later Step changes it again.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[23, 27, "step"], [43, 49, "entity"], [58, 63, "state"]] },
  "arc": { term: "Arc", searchNames: ["Arc","Arcs"], definition: "A move a Step makes: into a State, out of one, or between two. Nothing declares arcs; the report composes them from the Scenarios.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[9, 13, "step"], [28, 33, "state"]] },
  "lifecycle": { term: "Lifecycle", searchNames: ["Lifecycle","Lifecycles","Machine","Machines"], definition: "An Entity's States and Arcs, showing how it is created, changes state, or is removed, derived from Scenario Steps across the model.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[3, 9, "entity"], [12, 18, "state"], [23, 27, "arc"], [108, 113, "step"]] },
  "relation": { term: "Relation", searchNames: ["Relation","Relations","Relationship","Relationships"], definition: "A relationship between Entities, such as Shopper owns Orders, stating how many instances can relate on each side.", page: "entities", pageTitle: "Entities", anchor: "relations", mentions: [[23, 31, "entity"]] },
  "changed-by": { term: "Changed by", searchNames: ["Changed by","Changed bies"], definition: "The Capabilities whose Steps create, change, or remove this thing.", page: "entities", pageTitle: "Entities", anchor: "relations", mentions: [[4, 16, "capability"], [23, 28, "step"]] },
  "interface": { term: "Interface", searchNames: ["Interface","Interfaces"], definition: "A supported way for Actors to interact with the Product, such as a web app, a CLI, or a partner API.", page: "interfaces", pageTitle: "Interfaces", anchor: "", mentions: [[20, 26, "actor"], [48, 55, "product"]] },
  "interface-type": { term: "Interface type", searchNames: ["Interface type","Interface types"], definition: "The form an Interface takes: web, mobile app, desktop app, CLI, API, webhook, messaging, voice, device, or agent.", page: "interfaces", pageTitle: "Interfaces", anchor: "the-file", mentions: [[12, 21, "interface"]] },
  "capability-boundary": { term: "Capability boundary", searchNames: ["Capability boundary","Capability boundaries"], definition: "What an Interface, Experience, or Screen supports and excludes. Capability availability is declared on each Capability.", page: "interfaces", pageTitle: "Interfaces", anchor: "the-file", mentions: [[8, 17, "interface"], [19, 29, "experience"], [34, 40, "screen"], [64, 74, "capability"]] },
  "entry-point": { term: "Entry point", searchNames: ["Entry point","Entry points","Starts at","Starts ats"], definition: "A Product-facing route or address where an Actor arrives, such as a path, a deep link, or a command.", page: "interfaces", pageTitle: "Interfaces", anchor: "the-file", mentions: [[2, 9, "product"], [43, 48, "actor"]] },
  "experience": { term: "Experience", searchNames: ["Experience","Experiences"], definition: "A stable context for using the Product within one Interface, with a defined audience, access mode, and capability boundary.", page: "experiences", pageTitle: "Experiences", anchor: "", mentions: [[31, 38, "product"], [50, 59, "interface"]] },
  "access-mode": { term: "Access mode", searchNames: ["Access mode","Access modes"], definition: "Who may enter an Experience: public, authenticated, or restricted.", page: "experiences", pageTitle: "Experiences", anchor: "the-file", mentions: [[17, 27, "experience"]] },
  "screen": { term: "Screen", searchNames: ["Screen","Screens"], definition: "A meaningful visual view, named in the Product's own words, directly under an Interface or inside one of its Experiences.", page: "screens", pageTitle: "Screens", anchor: "", mentions: [[39, 46, "product"], [78, 87, "interface"], [109, 120, "experience"]] },
  "view-state": { term: "View state", searchNames: ["View state","View states"], definition: "A condition of a Screen, such as empty, populated, or unauthorized. It describes the view rather than an Entity's Lifecycle.", page: "screens", pageTitle: "Screens", anchor: "view-states-are-the-views-never-the-things", mentions: [[17, 23, "screen"], [105, 111, "entity"], [114, 123, "lifecycle"]] },
  "domain": { term: "Domain", searchNames: ["Domain","Domains"], definition: "A subject area of the Product, such as ordering or billing, that classifies related Capabilities and Entities.", page: "domains", pageTitle: "Domains", anchor: "", mentions: [[22, 29, "product"], [84, 96, "capability"], [101, 109, "entity"]] },
  "boundary": { term: "Boundary", searchNames: ["Boundary","Boundaries"], definition: "What a Domain takes in and what it leaves out, stated in the Product's own words.", page: "domains", pageTitle: "Domains", anchor: "the-file", mentions: [[7, 13, "domain"], [61, 68, "product"]] },
  "capability": { term: "Capability", searchNames: ["Capability","Capabilities"], definition: "A durable ability of the Product: what it can do, independent of any one route, command, or module.", page: "capabilities", pageTitle: "Capabilities", anchor: "", mentions: [[25, 32, "product"]] },
  "capability-scenario": { term: "Capability Scenario", searchNames: ["Capability Scenario","Capability Scenarios"], definition: "One observable acceptance case for a Capability: a trigger, typed Steps, and an outcome.", page: "capabilities", pageTitle: "Capabilities", anchor: "capability-scenarios", mentions: [[37, 47, "capability"], [66, 71, "step"]] },
  "context": { term: "Context", searchNames: ["Context","Contexts"], definition: "Where behavior is available, occurs, or is constrained: one Interface, Experience, or Screen. How specific it must be depends on what uses it.", page: "capabilities", pageTitle: "Capabilities", anchor: "availability", mentions: [[60, 69, "interface"], [71, 81, "experience"], [86, 92, "screen"]] },
  "step": { term: "Step", searchNames: ["Step","Steps"], definition: "One action or condition in a Scenario. Actions are performed by an Actor or the Product; effects on Entities are recorded explicitly.", page: "capabilities", pageTitle: "Capabilities", anchor: "what-a-step-does-to-the-products-things", mentions: [[67, 72, "actor"], [80, 87, "product"], [100, 108, "entity"]] },
  "ends-with": { term: "Ends with", searchNames: ["Ends with","Ends withs"], definition: "The last creation, change, or removal of each Entity instance in a Scenario, including the resulting State when specified.", page: "capabilities", pageTitle: "Capabilities", anchor: "what-a-step-does-to-the-products-things", mentions: [[46, 52, "entity"], [101, 106, "state"]] },
  "scenario-kind": { term: "Scenario kind", searchNames: ["Scenario kind","Scenario kinds"], definition: "A category for a Scenario, such as primary or edge, defined in the model's taxonomies.yaml.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-trigger": { term: "Trigger", searchNames: ["Trigger","Triggers"], definition: "The observable condition that starts the Scenario.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-outcome": { term: "Outcome", searchNames: ["Outcome","Outcomes"], definition: "The observable result once the Scenario has run.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-route": { term: "Route", searchNames: ["Route","Routes"], definition: "One named way the same Steps play out in different places. A route varies Context only; different Steps mean a different Scenario.", page: "capabilities", pageTitle: "Capabilities", anchor: "routes-steps-and-context-places", mentions: [[23, 28, "step"], [74, 81, "context"]] },
  "capability-scenario-decision-point": { term: "Decision point", searchNames: ["Decision point","Decision points"], definition: "A question with alternative branches that lead to the same Capability Scenario outcome. A different outcome requires another Scenario.", page: "capabilities", pageTitle: "Capabilities", anchor: "capability-scenario-decision-points", mentions: [[59, 78, "capability-scenario"]] },
  "capability-scenario-edge-case": { term: "Edge case", searchNames: ["Edge case","Edge cases"], definition: "A condition and its consequence recorded within a Scenario, without changing its path.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "journey": { term: "Journey", searchNames: ["Journey","Journeys"], definition: "An Actor goal whose successful completion requires several Capabilities working together.", page: "journeys", pageTitle: "Journeys", anchor: "", mentions: [[3, 8, "actor"], [59, 71, "capability"]] },
  "journey-scenario": { term: "Journey Scenario", searchNames: ["Journey Scenario","Journey Scenarios"], definition: "One path through a Journey, ending with its goal achieved or not achieved.", page: "journeys", pageTitle: "Journeys", anchor: "journey-scenarios", mentions: [[19, 26, "journey"]] },
  "success-criterion": { term: "Success criterion", searchNames: ["Success criterion","Success criterions"], definition: "How you know the Journey's goal was met.", page: "journeys", pageTitle: "Journeys", anchor: "the-file", mentions: [[17, 24, "journey"]] },
  "leaves-behind": { term: "Leaves behind", searchNames: ["Leaves behind","Leaves behinds"], definition: "The Entity instances created, changed, or removed by a Journey's achieved paths, with final States when specified.", page: "journeys", pageTitle: "Journeys", anchor: "the-file", mentions: [[4, 10, "entity"], [55, 62, "journey"], [92, 98, "state"]] },
  "journey-scenario-trigger": { term: "Trigger", searchNames: ["Trigger","Triggers"], definition: "The observable condition that starts the Journey Scenario.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [[41, 57, "journey-scenario"]] },
  "journey-scenario-outcome": { term: "Outcome", searchNames: ["Outcome","Outcomes"], definition: "Where the path ends, and whether the Journey's goal was achieved.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [[37, 44, "journey"]] },
  "result": { term: "Result", searchNames: ["Result","Results"], definition: "Whether this path achieves the Journey's goal: achieved, or not-achieved.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [[31, 38, "journey"]] },
  "journey-scenario-route": { term: "Route", searchNames: ["Route","Routes"], definition: "One named way the same Steps play out in different places. A route varies Context only; different Steps mean a different Journey Scenario.", page: "journeys", pageTitle: "Journeys", anchor: "steps-and-routes", mentions: [[23, 28, "step"], [74, 81, "context"], [121, 137, "journey-scenario"]] },
  "journey-scenario-decision-point": { term: "Decision point", searchNames: ["Decision point","Decision points"], definition: "A question with alternative branches that preserve the Journey Scenario's Capability sequence and outcome.", page: "journeys", pageTitle: "Journeys", anchor: "journey-scenario-decision-points", mentions: [[55, 71, "journey-scenario"], [74, 84, "capability"]] },
  "journey-scenario-edge-case": { term: "Edge case", searchNames: ["Edge case","Edge cases"], definition: "A condition and its consequence recorded within a Scenario, without changing its path.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [] },
  "business-rule": { term: "Business Rule", searchNames: ["Business Rule","Business Rules","Rule","Rules"], definition: "A durable assertion that must stay true, and the only place the model says who may act.", page: "business-rules", pageTitle: "Business Rules", anchor: "", mentions: [] },
  "applies-to": { term: "Applies to", searchNames: ["Applies to","Applies tos","Binding","Bindings"], definition: "What a Rule constrains: a resource, a Context it holds in, or an operation on a thing.", page: "business-rules", pageTitle: "Business Rules", anchor: "behavioral-and-context-targets", mentions: [[7, 11, "business-rule"], [38, 45, "context"]] },
  "operation": { term: "Operation", searchNames: ["Operation","Operations","What it changes","What it changess"], definition: "What may be done to a thing: creates, changes, removes, or reads. A Step calls it an effect; a Business Rule selects the same word as an operation.", page: "business-rules", pageTitle: "Business Rules", anchor: "entity-targets-an-operation-on-a-thing", mentions: [[68, 72, "step"], [95, 108, "business-rule"]] },
  "who-may": { term: "Who may", searchNames: ["Who may","Who mays","Permission","Permissions"], definition: "To allow an operation, at least one grant must match in every applicable permission Rule. An empty grant list forbids it.", page: "business-rules", pageTitle: "Business Rules", anchor: "permission", mentions: [[84, 88, "business-rule"]] },
  "reference": { term: "Reference", searchNames: ["Reference","References"], definition: "A pointer to material outside the model, such as code, a spec, or a screenshot, saying what it is and why it is attached.", page: "references", pageTitle: "References", anchor: "asset-or-reference", mentions: [] },
  "reference-kind": { term: "Reference kind", searchNames: ["Reference kind","Reference kinds"], definition: "What the referenced material is: code, prd, spec, proposal, doc, adr, visual, or research.", page: "references", pageTitle: "References", anchor: "kind-and-role", mentions: [] },
  "reference-role": { term: "Reference role", searchNames: ["Reference role","Reference roles"], definition: "Why a Reference is attached: intent helps define the Product, implementation points to what was built, and context provides background.", page: "references", pageTitle: "References", anchor: "kind-and-role", mentions: [[6, 15, "reference"], [53, 60, "product"]] }
} as const satisfies Record<string, VocabularyEntry>

/** Every addressable term. A surface naming one that is gone fails to compile. */
export type VocabularySlug = keyof typeof VOCABULARY

/**
 * Each page's first declared term. For pages included in the vocabulary panel,
 * it appears in the section head, with the page's other terms beneath it.
 */
export const VOCABULARY_LEADS: Readonly<Record<string, VocabularySlug>> = {
  "product-model": "product-model",
  "product": "product",
  "entities": "entity",
  "interfaces": "interface",
  "experiences": "experience",
  "screens": "screen",
  "domains": "domain",
  "capabilities": "capability",
  "journeys": "journey",
  "business-rules": "business-rule",
  "references": "reference"
}
