/**
 * Generated by `npm run vocabulary` from the `terms:` frontmatter of the owning documentation pages.
 *
 * Do not edit by hand: run `npm run vocabulary` after changing a page's terms,
 * and `npm run check` fails while this file and docs/ disagree.
 */

export interface VocabularyEntry {
  /** The word as the report renders it. */
  term: string
  /** The term's name, aliases, and their plurals, generated from its owning page. */
  searchNames: readonly string[]
  /** One line. The owning page carries the explanation. */
  definition: string
  /** The docs page that owns it, and the heading to land on. */
  page: string
  anchor: string
  /** How the owning page names itself. */
  pageTitle: string
  /**
   * Where this definition leans on another term: from, to, slug — slices of the
   * definition above. Resolved once at generation so every surface links the
   * same words, and left as offsets so the definition stays one searchable
   * string.
   */
  mentions: readonly (readonly [number, number, string])[]
}

export const VOCABULARY = {
  "product-model": { term: "Product Model", searchNames: ["Product Model","Product Models"], definition: "The .businesslens/ folder: one product described in Markdown files, tracked in Git, and free to point at the repository's code.", page: "product-model", pageTitle: "Model overview", anchor: "the-shape-of-a-model", mentions: [] },
  "intent": { term: "Intent", searchNames: ["Intent","Intents"], definition: "Why a resource exists and which outcome it protects, never a restatement of what it does.", page: "product-model", pageTitle: "Model overview", anchor: "authoring-conventions", mentions: [] },
  "coverage": { term: "Coverage", searchNames: ["Coverage","Coverages"], definition: "What the model sets out to describe, what it covers, what it leaves out on purpose, and its known gaps.", page: "product-model", pageTitle: "Model overview", anchor: "coverage", mentions: [] },
  "resource-type": { term: "Resource type", searchNames: ["Resource type","Resource types"], definition: "A kind of resource, such as Entity or Capability, decided by where its file sits in the Product Model.", page: "product-model", pageTitle: "Model overview", anchor: "what-belongs-in-a-model", mentions: [[28, 34, "entity"], [38, 48, "capability"], [88, 101, "product-model"]] },
  "product": { term: "Product", searchNames: ["Product","Products"], definition: "The one coherent value promise this model describes, and the boundary drawn around it.", page: "product", pageTitle: "Product", anchor: "", mentions: [] },
  "entity": { term: "Entity", searchNames: ["Entity","Entities"], definition: "A thing the Product keeps or reasons about, including the people and systems that act on it.", page: "entities", pageTitle: "Entities", anchor: "", mentions: [[12, 19, "product"]] },
  "actor": { term: "Actor", searchNames: ["Actor","Actors"], definition: "An Entity that acts on the Product. Actor is a role a thing plays where it acts, never a resource type of its own.", page: "entities", pageTitle: "Entities", anchor: "actors-an-entity-that-acts", mentions: [[3, 9, "entity"], [27, 34, "product"]] },
  "entity-kind": { term: "Entity kind", searchNames: ["Entity kind","Entity kinds"], definition: "Whether an Entity that acts on the Product is a person or a system.", page: "entities", pageTitle: "Entities", anchor: "actors-an-entity-that-acts", mentions: [[11, 17, "entity"], [35, 42, "product"]] },
  "acts": { term: "Acts", searchNames: ["Acts","Actss"], definition: "Which side of the boundary an Actor acts from: internal to the organisation running the Product, or external to it.", page: "entities", pageTitle: "Entities", anchor: "external-systems-direction-decides", mentions: [[30, 35, "actor"], [88, 95, "product"]] },
  "information-kept": { term: "Information kept", searchNames: ["Information kept","Information kepts"], definition: "Named facts the Product keeps about an Entity, such as Total charged. Each is cited by name; storage details and data types stay outside the model.", page: "entities", pageTitle: "Entities", anchor: "named-facts", mentions: [[16, 23, "product"], [39, 45, "entity"]] },
  "state": { term: "State", searchNames: ["State","States"], definition: "A named condition an Entity can be in, such as Pending or Refunded. Scenario Steps move it between States.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[21, 27, "entity"], [77, 82, "step"]] },
  "left-here-by": { term: "Left here by", searchNames: ["Left here by","Left here bies"], definition: "Scenarios containing a Step that puts this Entity in this State, even if a later Step changes it again.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[23, 27, "step"], [43, 49, "entity"], [58, 63, "state"]] },
  "arc": { term: "Arc", searchNames: ["Arc","Arcs"], definition: "A move a Step makes: into a State, out of one, or between two. Nothing declares Arcs; they are composed from the Scenarios.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[9, 13, "step"], [28, 33, "state"]] },
  "lifecycle": { term: "Lifecycle", searchNames: ["Lifecycle","Lifecycles","Machine","Machines"], definition: "An Entity's States and Arcs, showing how it is created, changes State, or is removed, composed from Scenario Steps across the model.", page: "entities", pageTitle: "Entities", anchor: "states-and-the-lifecycle-nobody-authors", mentions: [[3, 9, "entity"], [12, 18, "state"], [23, 27, "arc"], [109, 114, "step"]] },
  "relation": { term: "Relation", searchNames: ["Relation","Relations","Relationship","Relationships"], definition: "A relationship between Entities, such as Shopper owns Orders, stating how many instances can relate on each side.", page: "entities", pageTitle: "Entities", anchor: "relations", mentions: [[23, 31, "entity"]] },
  "changed-by": { term: "Changed by", searchNames: ["Changed by","Changed bies"], definition: "The Capabilities whose Steps create, change, or remove this thing.", page: "entities", pageTitle: "Entities", anchor: "how-it-connects", mentions: [[4, 16, "capability"], [23, 28, "step"]] },
  "interface": { term: "Interface", searchNames: ["Interface","Interfaces"], definition: "A supported way for Actors to reach the Product, such as a web app, a mobile app, a CLI, a partner API or an inbound webhook.", page: "interfaces", pageTitle: "Interfaces", anchor: "", mentions: [[20, 26, "actor"], [40, 47, "product"]] },
  "interface-type": { term: "Interface type", searchNames: ["Interface type","Interface types"], definition: "The form an Interface takes: web, mobile app, desktop app, CLI, API, webhook, messaging, voice, device, or agent.", page: "interfaces", pageTitle: "Interfaces", anchor: "the-file", mentions: [[12, 21, "interface"]] },
  "entry-point": { term: "Entry point", searchNames: ["Entry point","Entry points","Starts at","Starts ats"], definition: "An address where an Actor arrives, such as a path, a deep link or a command.", page: "interfaces", pageTitle: "Interfaces", anchor: "the-file", mentions: [[20, 25, "actor"]] },
  "navigation": { term: "Navigation", searchNames: ["Navigation","Navigations"], definition: "The Screens an Actor can reach from anywhere inside an Interface or Experience, such as a cart or a search.", page: "interfaces", pageTitle: "Interfaces", anchor: "navigation", mentions: [[4, 11, "screen"], [15, 20, "actor"], [55, 64, "interface"], [68, 78, "experience"]] },
  "experience": { term: "Experience", searchNames: ["Experience","Experiences"], definition: "One part of an Interface, such as its public, signed-in or admin part, defined by who is there and what they can do.", page: "interfaces", pageTitle: "Interfaces", anchor: "experiences", mentions: [[15, 24, "interface"]] },
  "access-mode": { term: "Access mode", searchNames: ["Access mode","Access modes"], definition: "Who may enter an Experience: anyone (public), anyone signed in (authenticated), or only the roles that administer the Product (restricted).", page: "interfaces", pageTitle: "Interfaces", anchor: "experience-file", mentions: [[17, 27, "experience"], [118, 125, "product"]] },
  "screen": { term: "Screen", searchNames: ["Screen","Screens"], definition: "A place inside an Interface or Experience, named in the Product's own words, where an Actor sees facts and finds abilities.", page: "interfaces", pageTitle: "Interfaces", anchor: "screens", mentions: [[18, 27, "interface"], [31, 41, "experience"], [56, 63, "product"], [86, 91, "actor"]] },
  "child-screen": { term: "Child Screen", searchNames: ["Child Screen","Child Screens","Nested Screen","Nested Screens"], definition: "A Screen inside another Screen that works on the same selected thing or process, such as a tab of one record or a step of a wizard.", page: "interfaces", pageTitle: "Interfaces", anchor: "screens-nest", mentions: [[2, 8, "screen"]] },
  "domain": { term: "Domain", searchNames: ["Domain","Domains"], definition: "A subject area of the Product, such as ordering or billing, that classifies related Capabilities and Entities.", page: "domains", pageTitle: "Domains", anchor: "", mentions: [[22, 29, "product"], [84, 96, "capability"], [101, 109, "entity"]] },
  "boundary": { term: "Boundary", searchNames: ["Boundary","Boundaries"], definition: "What a Domain takes in and what it leaves out, stated in the Product's own words.", page: "domains", pageTitle: "Domains", anchor: "the-file", mentions: [[7, 13, "domain"], [61, 68, "product"]] },
  "capability": { term: "Capability", searchNames: ["Capability","Capabilities"], definition: "A durable thing the Product lets someone do, such as checkout or order cancellation, independent of any one route, command or module.", page: "capabilities", pageTitle: "Capabilities", anchor: "", mentions: [[20, 27, "product"]] },
  "capability-scenario": { term: "Capability Scenario", searchNames: ["Capability Scenario","Capability Scenarios"], definition: "One acceptance case for a Capability: what starts it, its Steps, and the outcome.", page: "capabilities", pageTitle: "Capabilities", anchor: "capability-scenarios", mentions: [[26, 36, "capability"], [58, 63, "step"]] },
  "context": { term: "Context", searchNames: ["Context","Contexts"], definition: "A place where behavior is offered or happens: one Interface, Experience or Screen.", page: "capabilities", pageTitle: "Capabilities", anchor: "availability", mentions: [[50, 59, "interface"], [61, 71, "experience"], [75, 81, "screen"]] },
  "step": { term: "Step", searchNames: ["Step","Steps"], definition: "One action or condition in a Scenario, by an Actor or the Product, saying what it does to the Product's Entities.", page: "capabilities", pageTitle: "Capabilities", anchor: "what-a-step-does-to-the-products-things", mentions: [[45, 50, "actor"], [58, 65, "product"], [104, 112, "entity"]] },
  "ends-with": { term: "Ends with", searchNames: ["Ends with","Ends withs"], definition: "Where each Entity a Scenario touches is left: its last creation, change or removal, with the resulting State when there is one.", page: "capabilities", pageTitle: "Capabilities", anchor: "what-a-step-does-to-the-products-things", mentions: [[11, 17, "entity"], [103, 108, "state"]] },
  "scenario-kind": { term: "Scenario kind", searchNames: ["Scenario kind","Scenario kinds"], definition: "A category for a Scenario, such as primary or edge, defined in the model's taxonomies.yaml.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-trigger": { term: "Trigger", searchNames: ["Trigger","Triggers"], definition: "What starts the Scenario.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-outcome": { term: "Outcome", searchNames: ["Outcome","Outcomes"], definition: "What is true once the Scenario has run.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "capability-scenario-route": { term: "Route", searchNames: ["Route","Routes"], definition: "One named way the same Steps play out in different places, such as web and mobile. Different Steps mean a different Scenario.", page: "capabilities", pageTitle: "Capabilities", anchor: "routes-steps-and-context-places", mentions: [[23, 28, "step"]] },
  "capability-scenario-decision-point": { term: "Decision point", searchNames: ["Decision point","Decision points"], definition: "A question inside a Scenario whose branches all reach the same outcome. A different outcome is another Scenario.", page: "capabilities", pageTitle: "Capabilities", anchor: "capability-scenario-decision-points", mentions: [] },
  "capability-scenario-edge-case": { term: "Edge case", searchNames: ["Edge case","Edge cases"], definition: "A condition and its consequence noted within a Scenario, without changing its path.", page: "capabilities", pageTitle: "Capabilities", anchor: "the-capability-scenario-file", mentions: [] },
  "journey": { term: "Journey", searchNames: ["Journey","Journeys"], definition: "A goal where the Product carries one person from one Capability into the next until the goal is met, such as browse and buy.", page: "journeys", pageTitle: "Journeys", anchor: "", mentions: [[17, 24, "product"], [53, 63, "capability"]] },
  "journey-scenario": { term: "Journey Scenario", searchNames: ["Journey Scenario","Journey Scenarios"], definition: "One path through a Journey, ending with its goal achieved or not achieved.", page: "journeys", pageTitle: "Journeys", anchor: "journey-scenarios", mentions: [[19, 26, "journey"]] },
  "success-criterion": { term: "Success criterion", searchNames: ["Success criterion","Success criterions"], definition: "How you know the Journey's goal was met.", page: "journeys", pageTitle: "Journeys", anchor: "the-file", mentions: [[17, 24, "journey"]] },
  "leaves-behind": { term: "Leaves behind", searchNames: ["Leaves behind","Leaves behinds"], definition: "What a Journey's successful paths create, change or remove, with final States where there are any.", page: "journeys", pageTitle: "Journeys", anchor: "the-file", mentions: [[7, 14, "journey"], [71, 77, "state"]] },
  "journey-scenario-trigger": { term: "Trigger", searchNames: ["Trigger","Triggers"], definition: "What starts the Journey Scenario: the person setting out after the goal.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [[16, 32, "journey-scenario"]] },
  "journey-scenario-outcome": { term: "Outcome", searchNames: ["Outcome","Outcomes"], definition: "Where the path ends, and whether the Journey's goal was achieved.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [[37, 44, "journey"]] },
  "result": { term: "Result", searchNames: ["Result","Results"], definition: "Whether this path achieves the Journey's goal: achieved, or not-achieved.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [[31, 38, "journey"]] },
  "journey-scenario-route": { term: "Route", searchNames: ["Route","Routes"], definition: "One named way the same Steps play out in different places, such as web and mobile. Different Steps mean a different Journey Scenario.", page: "journeys", pageTitle: "Journeys", anchor: "steps-and-routes", mentions: [[23, 28, "step"], [116, 132, "journey-scenario"]] },
  "journey-scenario-decision-point": { term: "Decision point", searchNames: ["Decision point","Decision points"], definition: "A question inside a Journey Scenario whose branches keep the same Capabilities and outcome.", page: "journeys", pageTitle: "Journeys", anchor: "journey-scenario-decision-points", mentions: [[20, 36, "journey-scenario"], [66, 78, "capability"]] },
  "journey-scenario-edge-case": { term: "Edge case", searchNames: ["Edge case","Edge cases"], definition: "A condition and its consequence noted within a Scenario, without changing its path.", page: "journeys", pageTitle: "Journeys", anchor: "the-journey-scenario-file", mentions: [] },
  "business-rule": { term: "Business Rule", searchNames: ["Business Rule","Business Rules","Rule","Rules"], definition: "Something that must always hold in the Product, or who may do what. It is the only place the model says who may act.", page: "business-rules", pageTitle: "Business Rules", anchor: "", mentions: [[39, 46, "product"]] },
  "applies-to": { term: "Applies to", searchNames: ["Applies to","Applies tos","Binding","Bindings"], definition: "What a Rule governs: a Capability, a Journey, one of their Scenarios, a place, or an operation on a thing.", page: "business-rules", pageTitle: "Business Rules", anchor: "behavioral-and-context-targets", mentions: [[7, 11, "business-rule"], [23, 33, "capability"], [37, 44, "journey"]] },
  "operation": { term: "Operation", searchNames: ["Operation","Operations","What it changes","What it changess"], definition: "What may be done to a thing: creates, changes, removes, or reads. A Step calls it an effect; a Business Rule selects the same word as an operation.", page: "business-rules", pageTitle: "Business Rules", anchor: "entity-targets-an-operation-on-a-thing", mentions: [[68, 72, "step"], [95, 108, "business-rule"]] },
  "who-may": { term: "Who may", searchNames: ["Who may","Who mays","Permission","Permissions"], definition: "Who may perform an operation on a thing, listed as grants in a Business Rule. An empty list means nobody may.", page: "business-rules", pageTitle: "Business Rules", anchor: "permission", mentions: [[63, 76, "business-rule"]] },
  "variation": { term: "Variation", searchNames: ["Variation","Variations"], definition: "A product that works in more than one supported way, with what decides which way applies: a feature flag, a setting, a plan, an A/B test or a version.", page: "variations", pageTitle: "Variations", anchor: "", mentions: [] },
  "alternative": { term: "Alternative", searchNames: ["Alternative","Alternatives"], definition: "One of the supported ways in a Variation, still a complete resource of its own type, with the condition that selects it.", page: "variations", pageTitle: "Variations", anchor: "the-file", mentions: [[31, 40, "variation"]] },
  "experiment": { term: "Experiment", searchNames: ["Experiment","Experiments"], definition: "A Variation whose alternatives are offered to compare outcomes, such as an A/B test, with who is assigned and how.", page: "variations", pageTitle: "Variations", anchor: "subtypes", mentions: [[2, 11, "variation"]] },
  "configuration": { term: "Configuration", searchNames: ["Configuration","Configurations"], definition: "A Variation chosen by a setting, feature flag, plan or deployment.", page: "variations", pageTitle: "Variations", anchor: "subtypes", mentions: [[2, 11, "variation"]] },
  "version": { term: "Version", searchNames: ["Version","Versions"], definition: "A Variation whose alternatives are contracts or forms that stay supported together, such as API v1 and v2, each with a label.", page: "variations", pageTitle: "Variations", anchor: "subtypes", mentions: [[2, 11, "variation"]] },
  "reference": { term: "Reference", searchNames: ["Reference","References"], definition: "A pointer to material outside the model, such as code, a spec, or a screenshot, saying what it is and why it is attached.", page: "references", pageTitle: "References", anchor: "asset-or-reference", mentions: [] },
  "reference-kind": { term: "Reference kind", searchNames: ["Reference kind","Reference kinds"], definition: "What the referenced material is: code, prd, spec, proposal, doc, adr, visual, or research.", page: "references", pageTitle: "References", anchor: "kind-and-role", mentions: [] },
  "reference-role": { term: "Reference role", searchNames: ["Reference role","Reference roles"], definition: "Why a Reference is attached: intent helps define the Product, implementation points to what was built, and context provides background.", page: "references", pageTitle: "References", anchor: "kind-and-role", mentions: [[6, 15, "reference"], [53, 60, "product"]] }
} as const satisfies Record<string, VocabularyEntry>

/** Every addressable term. A surface naming one that is gone fails to compile. */
export type VocabularySlug = keyof typeof VOCABULARY

/**
 * Each page's first declared term. For pages included in the vocabulary panel,
 * it appears in the section head, with the page's other terms beneath it.
 */
export const VOCABULARY_LEADS: Readonly<Record<string, VocabularySlug>> = {
  "product-model": "product-model",
  "product": "product",
  "entities": "entity",
  "interfaces": "interface",
  "domains": "domain",
  "capabilities": "capability",
  "journeys": "journey",
  "business-rules": "business-rule",
  "variations": "variation",
  "references": "reference"
}
